spring.application.name=cp2-brinquedos

# ==================================================
# Configuração do Banco de Dados Oracle FIAP
# Substitua usuario e senha pelas suas credenciais
# ==================================================
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm561760
spring.datasource.password=101105
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==================================================
# Configuração JPA / Hibernate
# ==================================================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================================================
# Servidor Tomcat
# ==================================================
server.port=8080
